### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by dennios** [doggybenny/RootLessInstallerDEB#2]
Please add:
byehomebottombarx_1.0.1
breadcrumbsaway_1.1
realcc_1.0.1
3dnodiv_1.0
hidedots11_0.0.1-1
croutons_1.0-1
Thx :)

Edit: videohud_2.3

**Comment by alexp9982** [comment]
And LockGlyphX
And Snowboard
And SmartVolumeControl2

**Comment by MaybeAdmin** [comment]
Hello, please make a pull request with a txt file listing all the tweaks. This is not an "issue".
